apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceapp-v1-deployment
  labels:
    app: myinsuranceapp-v1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myinsuranceapp-v1
  template:
    metadata:
      labels:
        app: myinsuranceapp-v1
    spec:
      containers:
      - name: myinsuranceapp-v1
        image: duygugurbuzyildiz/myinsuranceapp-v1:v1.2
        ports:
        - name: http
          containerPort: 5000
