apiVersion: v1
kind: Service
metadata:
  name: myinsuranceapp-v1
  labels:
    app: myinsuranceapp-v1
spec:
  selector:
    app: myinsuranceapp-v1
  type: NodePort
  ports:
  - port: 5000
    targetPort: http
    nodePort: 31012
    protocol: TCP
    name: http
